kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: dittnav
  namespace: min-side
  labels:
    team: min-side
  annotations:
    nais.io/read-only-file-system: "false"
    config.linkerd.io/proxy-memory-limit: "512Mi"
    config.linkerd.io/proxy-memory-request: "128Mi"
spec:
  envFrom:
    - secret: dittnav-secrets
  image: {{version}}
  ingresses:
    - "https://www.nav.no/person/dittnav"
    - "https://www.intern.nav.no/person/dittnav"
  liveness:
    path: person/dittnav/internal/isAlive
    port: 8080
    initialDelay: 10
  port: 8080
  prometheus:
    enabled: true
    path: person/dittnav/internal/metrics
  readiness:
    path: person/dittnav/internal/isReady
    port: 8080
    initialDelay: 10
  replicas:
    min: 4
    max: 6
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: "3"
      memory: 1268Mi
    requests:
      cpu: 500m
      memory: 1024Mi
  env:
    - name: VEIENTILARBEID_URL
      value: "https://veientilarbeid.nav.no"
