export const ADD_BESKJEDER = 'ADD_BESKJEDER';
export const ADD_INAKTIVE_BESKJEDER = 'ADD_INAKTIVE_BESKJEDER';
export const ADD_INAKTIV_BESKJED = 'ADD_INAKTIV_BESKJED';
export const REMOVE_BESKJED = 'REMOVE_AKTIV_BESKJED';
