export const ADD_BESKJEDER = 'ADD_BESKJEDER';

export const REMOVE_BESKJED = 'REMOVE_AKTIV_BESKJED';

export const ADD_OPPGAVER = 'ADD_OPPGAVER';

export const ADD_INNBOKSER = 'ADD_INNBOKSER';

export const ADD_INAKTIVE_BESKJEDER = 'ADD_INAKTIVE_BESKJEDER';

export const ADD_INAKTIV_BESKJED = 'ADD_INAKTIV_BESKJED';

export const ADD_INAKTIVE_OPPGAVER = 'ADD_INAKTIVE_OPPGAVER';

export const ADD_INAKTIVE_INNBOKSER = 'ADD_INAKTIVE_INNBOKSER';

export const ADD_INNLOGGING = 'ADD_INNLOGGING';

export const SET_BESKJEDER_LOADING = 'SET_BESKJEDER_LOADING';

export const SET_INAKTIVE_BESKJEDER_LOADING = 'SET_INAKTIVE_BESKJEDER_LOADING';

export const BESKJEDER_ERROR = 'BESKJEDER_ERROR';

export const OPPGAVER_ERROR = 'OPPGAVER_ERROR';

export const INNBOKSER_ERROR = 'INNBOKSER_ERROR';

export const INAKTIVE_BESKJEDER_ERROR = 'INAKTIVE_BESKJEDER_ERROR';

export const INAKTIVE_OPPGAVER_ERROR = 'INAKTIVE_OPPGAVER_ERROR';

export const INAKTIVE_INNBOKSER_ERROR = 'INAKTIVE_INNBOKSER_ERROR';

export const INNLOGGING_ERROR = 'INNLOGGING_ERROR';
