name: Add pull requests to project

on:
  pull_request:
    types:
      - opened

jobs:
  add-to-project:
    name: Add pull request to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@138f841d13c74081782bf3227bb93143372af85b
        with:
          project-url: https://github.com/orgs/navikt/projects/52
          github-token: ${{ secrets.PROJECT_PAT }}