name: Kjør ende-til-ende-tester ved pull-request

on:
  pull_request:

jobs:
  run-end-to-end-tests:
    runs-on: ubuntu-latest
    steps:
      - name: 'Sjekk ut koden for dette repo-et'
        uses: actions/checkout@v2
      - name: 'Sjekk ut dittnav-docker-compose'
        uses: actions/checkout@v2
        with:
          repository: navikt/dittnav-docker-compose
          path: dittnav-docker-compose
          token: ${{ secrets.DOCKER_PKG_TOKEN }}
      - uses: actions/setup-java@v1
        with:
          java-version: '13'
      - name: 'Pull dittnav-docker-compose'
        run: |
          echo "${{ secrets.DOCKER_PKG_TOKEN }}" | docker login --username "x-access-token" --password-stdin https://docker.pkg.github.com
          cd dittnav-docker-compose
          docker-compose pull
          cd ..
      - name: 'Docker build and tag latest'
        run: |
          ./gradlew clean assemble
          APP_NAME=$(echo $GITHUB_REPOSITORY | rev | cut -f1 -d"/" | rev )
          IMAGE_BASE="docker.pkg.github.com/$GITHUB_REPOSITORY/$APP_NAME"
          IMAGE_LATEST="$IMAGE_BASE:latest"
          docker build --tag $IMAGE_LATEST .
      - name: 'Run end-to-end-tests'
        run: |
          cd dittnav-docker-compose
          ./gradlew test