name: Bygg branch

on:
  push:
    branches-ignore:
      - master
      - main

jobs:
  build-branch:
    runs-on: ubuntu-latest
    steps:

      - name: Sjekk ut koden
        uses: actions/checkout@v2

      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: '17.x'

      - name: Finn cache-variabler
        uses: navikt/pb-common-gh-actions/cache-prep@v2

      - name: Sett opp cache
        uses: actions/cache@v2
        with:
          path: |
            ${{ env.CACHE_PATHS }}
          key: ${{ runner.os }}${{ env.CACHE_KEY_NAMESPACE }}${{ hashFiles(env.CACHE_KEY_HASHED_PATH) }}

      - name: Bygg prosjekt og kjør tester
        uses: navikt/pb-common-gh-actions/build@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
